# Competition: Race Car

Learn to race a car using the [Gymnasium CarRacing environment](https://gymnasium.farama.org/environments/box2d/car_racing/). Use Deep RL. You can use algorithms from 
* [Stable Baseline 3](https://stable-baselines3.readthedocs.io/en/master/)
* [CleanLR](https://github.com/vwxyzjn/cleanrl)


## Setup

You need:
* Gymnasium (see [Installation Instructions](../common/Setup_Gymnasium.ipynb))
* Patched `gym-classics-1.0.0+internal.rev1` or later (see [Installation instructions](../common/Setup_patched_gym_classics.ipynb))

In [1]:
import numpy as np
np.set_printoptions(precision=2)

In [2]:
import gymnasium as gym
import gym_classics
gym_classics.register('gymnasium')

In [3]:
# download if missing
import urllib.request
import os

def download(file, base_url):
    if not os.path.exists(file):
        urllib.request.urlretrieve(base_url + file, file)

download("gymnasium_display_recorder.py", 
         "https://raw.githubusercontent.com/mhahsler/Introduction_to_Reinforcement_Learning/refs/heads/main/common/")

## Run The Environment

In [12]:
def run_episode(agent_function, env, max_steps=1000, verbose = True, render = True):
    """Run one episode in the environment using the provided agent."""

    # Reset the environment to generate the first observation (observation and state are the same in fully observable environments)
    observation, info = env.reset()
    
    # run one episode
    G = 0 # undiscounted episode return
    for i in range(max_steps):
        # call the agent function to select an action
        action = agent_function(observation)

        # step: execute an action in the environment
        observation_prime, reward, terminated, truncated, info = env.step(action)

        if verbose:
            print (f"Step {i+1}: Obs {np.round(observation, 1)} -> Action {action} - > Reward {np.round(reward,1)}, Obs' {np.round(observation_prime,1)}")

        observation = observation_prime
        G += reward

        # render the environment
        if render:
            env.render()

        if terminated:
            break
  
    if verbose:
        print(f"Episode Return: {G}")
    
    return G

## Simple Agent Function

In [5]:
def speed_kills_driver(observation): 
    """A random agent that selects actions uniformly at random. It ignores the observation.
    
    Actions
    0: do nothing
    1: steer right
    2: steer left
    3: gas
    4: brake
    """
    return np.random.choice([0, 1, 2, 3, 4], p=[0, 0.1, 0.1, 0.8, 0])

## Drive to See the Observation Structure

In [7]:
env = gym.make("CarRacing-v3", continuous=False, render_mode=None)
run_episode(speed_kills_driver, env)
env.close()

Step 1: Obs [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]] -> Action 1 - > Reward 6.6, Obs' [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
Step 2: Obs [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
 

/home/mhahsler/github/Introduction_to_Reinforcement_Learning/.venv/lib/python3.12/site-packages/gymnasium/envs/box2d/car_racing.py:592: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym.make("CarRacing-v3", render_mode="rgb_array")
  gym.logger.warn(


Step 33: Obs [[[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 228 100]
  [100 228 100]
  [100 228 100]]

 [[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 228 100]
  [100 228 100]
  [100 228 100]]

 [[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 228 100]
  [100 228 100]
  [100 228 100]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]] -> Action 2 - > Reward -0.1, Obs' [[[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 227 100]
  [100 228 100]
  [100 228 100]]

 [[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 224 100]
  [100 228 100]
  [100 228 100]]

 [[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 221 100]
  [100 228 100]
  [100 228 100]]

 ...

 [[  

## Drive With Video

In [ ]:
from gymnasium_display_recorder import VideoWrapper, show

env = gym.make("CarRacing-v3", continuous=False, render_mode="rgb_array")
env_record = VideoWrapper(env, 'RC', render_fps=30)

G = run_episode(speed_kills_driver, env_record, verbose=False)
print(f"Episode Return: {G}")

show(env_record)
importenv.close()

Videos already exist, I remove them first!


/home/mhahsler/github/Introduction_to_Reinforcement_Learning/.venv/lib/python3.12/site-packages/gymnasium/wrappers/rendering.py:293: UserWarning: WARN: Overwriting existing videos at /home/mhahsler/github/Introduction_to_Reinforcement_Learning/DRL/videos folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(


Episode Return: -69.98590604026892
Showing: ./videos/video_RC-episode-0.mp4


## Evaluation

Every episode is a new random track.

In [11]:
from tqdm import tqdm

env = gym.make("CarRacing-v3", continuous=False, render_mode=None)

N = 10
score = 0.0
for _ in tqdm(range(N)):
    score += run_episode(speed_kills_driver, env, verbose=False)

print(f"Average Score over {N} races: {score/N}")

env.close()

  0%|          | 0/10 [00:00<?, ?it/s]/home/mhahsler/github/Introduction_to_Reinforcement_Learning/.venv/lib/python3.12/site-packages/gymnasium/envs/box2d/car_racing.py:592: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym.make("CarRacing-v3", render_mode="rgb_array")
  gym.logger.warn(
100%|██████████| 10/10 [00:34<00:00,  3.48s/it]

Average Score over 10 episodes: -56.08066779209088



&copy; 2025 [Michael Hahsler](http://michael.hahsler.net). 
This work is openly licensed under [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) License](https://creativecommons.org/licenses/by-sa/4.0/)

![CC BY-SA 4.0](https://licensebuttons.net/l/by-sa/3.0/88x31.png)